
nohup python main.py --reg_transform "sigmoid" --reg_sampler "random_inside" --reg_weight 150.0 --objective_option "weighted_average" --phi_nnl "tanh-tanh-softplus" --phi_nn_inputs "euc" --phi_include_xe --train_attacker_n_samples 500 --train_attacker_use_n_step_schedule --train_attacker_max_n_steps 20 --train_attacker_p_reuse 0.5 --train_attacker batch_warmstart --batch_warmstart_speedup_method sequential --batch_warmstart_sampling_method gaussian --random_seed 0 --affix "seed_0" --gpu 0 &> seed_0.out &

nohup python main.py --reg_transform "sigmoid" --reg_sampler "random_inside" --reg_weight 150.0 --objective_option "weighted_average" --phi_nnl "tanh-tanh-softplus" --phi_nn_inputs "euc" --phi_include_xe --train_attacker_n_samples 500 --train_attacker_use_n_step_schedule --train_attacker_max_n_steps 20 --train_attacker_p_reuse 0.5 --train_attacker batch_warmstart --batch_warmstart_speedup_method sequential --batch_warmstart_sampling_method gaussian --random_seed 1 --affix "seed_1" --gpu 0 &> seed_1.out &

nohup python main.py --reg_transform "sigmoid" --reg_sampler "random_inside" --reg_weight 150.0 --objective_option "weighted_average" --phi_nnl "tanh-tanh-softplus" --phi_nn_inputs "euc" --phi_include_xe --train_attacker_n_samples 500 --train_attacker_use_n_step_schedule --train_attacker_max_n_steps 20 --train_attacker_p_reuse 0.5 --train_attacker batch_warmstart --batch_warmstart_speedup_method sequential --batch_warmstart_sampling_method gaussian --random_seed 2 --affix "seed_2" --gpu 1 &> seed_2.out &

nohup python main.py --reg_transform "sigmoid" --reg_sampler "random_inside" --reg_weight 150.0 --objective_option "weighted_average" --phi_nnl "tanh-tanh-softplus" --phi_nn_inputs "euc" --phi_include_xe --train_attacker_n_samples 500 --train_attacker_use_n_step_schedule --train_attacker_max_n_steps 20 --train_attacker_p_reuse 0.5 --train_attacker batch_warmstart --batch_warmstart_speedup_method sequential --batch_warmstart_sampling_method gaussian --random_seed 3 --affix "seed_3" --gpu 2 &> seed_3.out &

nohup python main.py --reg_transform "sigmoid" --reg_sampler "random_inside" --reg_weight 150.0 --objective_option "weighted_average" --phi_nnl "tanh-tanh-softplus" --phi_nn_inputs "euc" --phi_include_xe --train_attacker_n_samples 500 --train_attacker_use_n_step_schedule --train_attacker_max_n_steps 20 --train_attacker_p_reuse 0.5 --train_attacker batch_warmstart --batch_warmstart_speedup_method sequential --batch_warmstart_sampling_method gaussian --random_seed 4 --affix "seed_4" --gpu 3 &> seed_4.out &